In [26]:
#1-1
def function(keyword, *numbers):
    if keyword == 'add':
        result = sum(numbers)         # 튜플에서는 += (X) / sum 쓰기!!
        print(f"The sum of the numbers is: {result}")
    elif keyword == 'multiply':
        result = 1
        for num in numbers:
            result *= num
        print(f"The product of the numbers is: {result}")

In [27]:
function('add',1,3)

The sum of the numbers is: 4


In [23]:
function('multiply',1,3)

The product of the numbers is: 3


In [28]:
#1-2
# 그냥 간단하게
def function2(keyword, num1, num2):
    if keyword == 'subtract':
        if num1> num2:
            result = num1-num2
        else:
            result = num2-num1
        print(f"The subtract is: {result}")
    elif keyword == 'divide':
        if num1 > num2:
            result = num1/num2
        else:
            result = num2/num1
        print(f"result is: {result}")

        
# args 사용할 때       
def function2(keyword, *args):
    if keyword == 'subtract':
        len(args) == 2
        result = max(args)-min(args)
        print(f"The difference is: {result}")
    elif keyword == 'divide':
        len(args) == 2
        result = max(args) / min(args)
        print(f"The divide is: {result}")

In [29]:
function2('subtract',1,2)

The subtract is: 1


In [32]:
function2('divide',4,40)

result is: 10.0


In [38]:
#1-3 ((((((이거 맞아?????????????))))))
# 오류 발생 원인 = 두 번째 수가 0일 경우
def function2(keyword, num1, num2):
    if keyword == 'subtract':
        if num1> num2:
            num2 != 0
            result = num1-num2
        else:
            num1 != 0
            result = num2-num1
        print(f"The subtract is: {result}")
    elif keyword == 'divide':
        if num1 > num2:
            num2 != 0
            result = num1/num2
        else:
            num1 != 0
            result = num2/num1
        print(f"result is: {result}")
        
def function2(keyword, *args): 
    len(args) == 2
    args[i] != 0
    if keyword == 'subtract':
        result = max(args)-min(args)
        print(f"The difference is: {result}")
    elif keyword == 'divide':
        result = max(args) / min(args)
        print(f"The divide is: {result}")

In [39]:
#1-3 ((((이거 맞아??????????????))))
def function2(keyword, *args):
    len(args) == 2
    if keyword == 'subtract':
        result = max(args)-min(args)
        print(f"The difference is: {result}")
    elif keyword == 'divide':
        args[i] != 0
        result = max(args) / min(args)
        print(f"The divide is: {result}")

In [40]:
#2-1
dictionary = {'철수':70, '영희':55, '민희':60, '영수':45, '영철':50}

In [ ]:
#2-2 ((((????????????????????))))
f = open('result.txt','w')
for i in range(6.10):
    f.write('studnet ')

In [ ]:
#3-1
class Calculator(self):
    def __init__(self,start_point=0):
        self.result = start_point
    def add(self,num):
        if not self.result:
            self.result = value
        else:
            self.result 
        
        

In [43]:
#4-1 (((????????????)))
import numpy as np

class Board_game():
    def __init__(self, initial = 0):
        self.minsu = initial
        self.yeongchul = initial
        self.winner = None

In [7]:
#4-2
class Board_game():
    def roll_dice(self):
        move =  np.random.randint((1,7))   # 구글에서는 포함이라는데 왜 gpt는 7이래????
        
    def minsu_stepping(self):
        move = self.roll_dice()
        self.minsu += move
        return self.minsu
    
    def yeongchul_stepping(self):
        move =  self.roll_dice()
        self.yeongchul += move
        return self.yeongchul

In [6]:
#4-3
def check(self): #self 넣어야 함?
    trial = 0
    
    while True:
        trial += 1
        agent = Board_game()
        Done = False
        if agent.minsu_stepping == 100:
            Done = True
            winner = 'minsu'
        elif agent.yeongchul_stepping == 100:
            Done = True
            winner = 'yeongchul'
        else:
            break
    return 


In [ ]:
#4-4
N_Trials = 1000
for i in range(N_Trials):
    

In [3]:
#5-1
import numpy as np

A = np.array([[1,1,1],
              [6,0,3],
              [2,1,2]])

b = np.array([10,18,15])

print("행렬 A:")
print(A)
print("행렬 b:")
print(b)

행렬 A:
[[1 1 1]
 [6 0 3]
 [2 1 2]]
행렬 b:
[10 18 15]


In [5]:
import numpy as np

# 연립방정식의 계수 행렬 A
A = np.array([[1, 1, 1],
              [6, 0, 3],
              [2, 1, 2]])

# 연립방정식의 우변 상수 벡터 b
b = np.array([10, 18, 15])

# 1. 행렬 A의 역행렬 계산
A_inv = np.linalg.inv(A)

# 2. 벡터 b를 열 벡터로 변환
b_column = b.reshape((-1, 1))
# 3. 해 계산
solution = np.dot(A_inv, b_column)

# 결과 출력
print("연립방정식의 해:")
print(solution)

연립방정식의 해:
[[1.]
 [5.]
 [4.]]
